services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: dns_logs
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
  virustotal_scanner:
    build: .
    container_name: virustotal_scanner
    volumes:
      - ./var-virustotal_logs:/app/logs
    networks:
      - mysql_network
    depends_on:
      - mysqldb
    restart: "no"

networks:
  mysql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.61.0.0/24
volumes:
  mysql_data: