global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.5:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.5:8080']