{
 "title": "Virus total scans",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total malicious scans",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n    -- Total number of all scans\n    COUNT(id) AS total_scans,\n    \n    -- Total number of scans where positives > 0\n    SUM(CASE WHEN positives > 0 THEN 1 ELSE 0 END) AS total_malicious_scans,\n    \n    -- Calculate the percentage of malicious scans\n    (SUM(CASE WHEN positives > 0 THEN 1 ELSE 0 END) / COUNT(id)) * 100 AS malicious_percentage\nFROM\n    virus_total.url_scans\nWHERE\n    $__timeFilter(scan_date);"
    }
   ]
  },
  {
   "title": "Total positive flags per day",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n    -- Calculate the start of the day in UNIX timestamp format\n    UNIX_TIMESTAMP(DATE(scan_date)) AS time_sec,\n    \n    -- Count the number of positive scans (Malicious Scans)\n    SUM(positives) AS total_positive\nFROM\n    virus_total.url_scans\nWHERE\n    -- Grafana time range filter\n    $__timeFilter(scan_date)\nGROUP BY\n    time_sec\nORDER BY\n    time_sec ASC;"
    }
   ]
  },
  {
   "title": "Total scans per day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "virus_total",
     "rawSql": "SELECT\n    -- 1. Obliczamy początek dnia z 'scan_date' (np. 2025-11-05 00:00:00)\n    UNIX_TIMESTAMP(DATE(scan_date)) AS time_sec,\n    \n    -- 2. Zliczamy całkowitą liczbę przeprowadzonych skanów danego dnia\n    COUNT(id) AS total_scans_per_day,\n    \n    -- 3. Sumujemy wszystkie \"pozytywne\" flagi (positives) z danego dnia\n    SUM(positives) AS total_positives_per_day\n    \nFROM\n    virus_total.url_scans\n-- Poprawiona nazwa tabeli zgodnie z Twoim zrzutem i wcześniejszymi uwagami\nWHERE\n    $__timeFilter(scan_date) \nGROUP BY\n    time_sec\nORDER BY\n    time_sec ASC;"
    }
   ]
  }
 ]
}