services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch
    hostname: elasticsearch
    network_mode: host
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - './etc-elasticsearch:/usr/share/elasticsearch/data'
    ports:
      - "9200:9200"
    restart: unless-stopped
    
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - './etc-mongo:/data/db'
    restart: unless-stopped

  graylog:
    image: graylog/graylog:6.1
    container_name: graylog
    hostname: graylog
    network_mode: host
    environment:
     - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
     - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
     - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
     - GRAYLOG_MONGODB_URI=mongodb://graylog:${MONGODB_PASSWORD}@127.0.0.1:27017/graylog
     - GRAYLOG_ELASTICSEARCH_HOSTS=http://127.0.0.1:9200
    volumes:
      - './etc-graylog:/etc/graylog'
      - './var-log-graylog:/var/log/graylog'
    depends_on:
      - mongo
      - elasticsearch
    restart: unless-stopped